/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "unavailable";
                            checks: {
                                /** @enum {string} */
                                database: "ok" | "error";
                            };
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "unavailable";
                            checks: {
                                /** @enum {string} */
                                database: "ok" | "error";
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                email: string | null;
                                firstName: string;
                                lastName: string;
                                username: string | null;
                                bio: string;
                                fiscalCode: string | null;
                                diet: string;
                                medicalNotes: string;
                                passport: {
                                    number: string | null;
                                    expiry: string | null;
                                    hasPhoto: boolean;
                                    photoVersion: string | null;
                                } | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        firstName?: string;
                        lastName?: string;
                        username?: string | null;
                        bio?: string;
                        fiscalCode?: string | null;
                        diet?: string;
                        medicalNotes?: string;
                        passport?: {
                            number: string;
                            expiry: string;
                        } | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                email: string | null;
                                firstName: string;
                                lastName: string;
                                username: string | null;
                                bio: string;
                                fiscalCode: string | null;
                                diet: string;
                                medicalNotes: string;
                                passport: {
                                    number: string | null;
                                    expiry: string | null;
                                    hasPhoto: boolean;
                                    photoVersion: string | null;
                                } | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/me/passport/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            passport: {
                                number: string | null;
                                expiry: string | null;
                                hasPhoto: boolean;
                                photoVersion: string | null;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/passport/photo/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                            expiresInSeconds: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            trips: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                destination: string | null;
                                /** Format: date */
                                startDate: string;
                                /** Format: date */
                                endDate: string;
                                totalDays: number;
                                crewCapacity: number | null;
                                inviteCode: string;
                                /** @enum {string} */
                                myRole: "coordinator" | "traveller";
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                crew: {
                                    /** Format: uuid */
                                    userId: string;
                                    firstName: string;
                                    lastName: string;
                                    username: string | null;
                                    /** @enum {string} */
                                    role: "coordinator" | "traveller";
                                    /** Format: date-time */
                                    joinedAt: string;
                                }[];
                                pendingInvitations: number;
                                mediaCount: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        destination?: string;
                        /** Format: date */
                        startDate: string;
                        /** Format: date */
                        endDate: string;
                        crewCapacity?: number;
                        invitees?: {
                            name: string;
                            /** Format: email */
                            email?: string;
                        }[];
                        emergencies?: {
                            title: string;
                            /** @default  */
                            subtitle?: string;
                            actionLabel: string;
                            phone: string;
                            /** @default false */
                            whatsapp?: boolean;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            trip: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                destination: string | null;
                                /** Format: date */
                                startDate: string;
                                /** Format: date */
                                endDate: string;
                                totalDays: number;
                                crewCapacity: number | null;
                                inviteCode: string;
                                /** @enum {string} */
                                myRole: "coordinator" | "traveller";
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                crew: {
                                    /** Format: uuid */
                                    userId: string;
                                    firstName: string;
                                    lastName: string;
                                    username: string | null;
                                    /** @enum {string} */
                                    role: "coordinator" | "traveller";
                                    /** Format: date-time */
                                    joinedAt: string;
                                }[];
                                invitations: {
                                    /** Format: uuid */
                                    id: string;
                                    name: string;
                                    email: string | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                }[];
                                days: {
                                    index: number;
                                    /** Format: date */
                                    date: string;
                                    stay: {
                                        name: string;
                                        address: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                        /** Format: date-time */
                                        updatedAt: string;
                                    } | null;
                                    activities: {
                                        /** Format: uuid */
                                        id: string;
                                        dayIndex: number;
                                        name: string;
                                        place: string;
                                        position: number;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    }[];
                                }[];
                                documents: {
                                    passport: {
                                        number: string | null;
                                        expiry: string | null;
                                        hasPhoto: boolean;
                                        photoVersion: string | null;
                                    } | null;
                                    customs: {
                                        code: string;
                                        note: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    } | null;
                                    transports: {
                                        /** Format: uuid */
                                        id: string;
                                        name: string;
                                        reference: string;
                                        /** @enum {string} */
                                        mode: "van" | "flight" | "ferry";
                                        docs: {
                                            /** Format: uuid */
                                            id: string;
                                            label: string;
                                            doc: {
                                                /** Format: uuid */
                                                id: string;
                                                /** @enum {string} */
                                                kind: "pdf" | "image" | "qr";
                                                title: string;
                                                subtitle: string;
                                                code: string;
                                                hasFile: boolean;
                                                originalName: string | null;
                                                mimeType: string | null;
                                                sizeBytes: number | null;
                                                /** Format: date-time */
                                                createdAt: string;
                                            } | null;
                                        }[];
                                    }[];
                                    insurance: {
                                        company: string;
                                        policy: string;
                                        coverage: string;
                                        emergencyPhone: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    } | null;
                                };
                                emergencies: {
                                    /** Format: uuid */
                                    id: string;
                                    title: string;
                                    subtitle: string;
                                    actionLabel: string;
                                    phone: string;
                                    whatsapp: boolean;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            trip: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                destination: string | null;
                                /** Format: date */
                                startDate: string;
                                /** Format: date */
                                endDate: string;
                                totalDays: number;
                                crewCapacity: number | null;
                                inviteCode: string;
                                /** @enum {string} */
                                myRole: "coordinator" | "traveller";
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                crew: {
                                    /** Format: uuid */
                                    userId: string;
                                    firstName: string;
                                    lastName: string;
                                    username: string | null;
                                    /** @enum {string} */
                                    role: "coordinator" | "traveller";
                                    /** Format: date-time */
                                    joinedAt: string;
                                }[];
                                invitations: {
                                    /** Format: uuid */
                                    id: string;
                                    name: string;
                                    email: string | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                }[];
                                days: {
                                    index: number;
                                    /** Format: date */
                                    date: string;
                                    stay: {
                                        name: string;
                                        address: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                        /** Format: date-time */
                                        updatedAt: string;
                                    } | null;
                                    activities: {
                                        /** Format: uuid */
                                        id: string;
                                        dayIndex: number;
                                        name: string;
                                        place: string;
                                        position: number;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    }[];
                                }[];
                                documents: {
                                    passport: {
                                        number: string | null;
                                        expiry: string | null;
                                        hasPhoto: boolean;
                                        photoVersion: string | null;
                                    } | null;
                                    customs: {
                                        code: string;
                                        note: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    } | null;
                                    transports: {
                                        /** Format: uuid */
                                        id: string;
                                        name: string;
                                        reference: string;
                                        /** @enum {string} */
                                        mode: "van" | "flight" | "ferry";
                                        docs: {
                                            /** Format: uuid */
                                            id: string;
                                            label: string;
                                            doc: {
                                                /** Format: uuid */
                                                id: string;
                                                /** @enum {string} */
                                                kind: "pdf" | "image" | "qr";
                                                title: string;
                                                subtitle: string;
                                                code: string;
                                                hasFile: boolean;
                                                originalName: string | null;
                                                mimeType: string | null;
                                                sizeBytes: number | null;
                                                /** Format: date-time */
                                                createdAt: string;
                                            } | null;
                                        }[];
                                    }[];
                                    insurance: {
                                        company: string;
                                        policy: string;
                                        coverage: string;
                                        emergencyPhone: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    } | null;
                                };
                                emergencies: {
                                    /** Format: uuid */
                                    id: string;
                                    title: string;
                                    subtitle: string;
                                    actionLabel: string;
                                    phone: string;
                                    whatsapp: boolean;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        destination?: string | null;
                        /** Format: date */
                        startDate?: string;
                        /** Format: date */
                        endDate?: string;
                        crewCapacity?: number | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            trip: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                destination: string | null;
                                /** Format: date */
                                startDate: string;
                                /** Format: date */
                                endDate: string;
                                totalDays: number;
                                crewCapacity: number | null;
                                inviteCode: string;
                                /** @enum {string} */
                                myRole: "coordinator" | "traveller";
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                crew: {
                                    /** Format: uuid */
                                    userId: string;
                                    firstName: string;
                                    lastName: string;
                                    username: string | null;
                                    /** @enum {string} */
                                    role: "coordinator" | "traveller";
                                    /** Format: date-time */
                                    joinedAt: string;
                                }[];
                                invitations: {
                                    /** Format: uuid */
                                    id: string;
                                    name: string;
                                    email: string | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                }[];
                                days: {
                                    index: number;
                                    /** Format: date */
                                    date: string;
                                    stay: {
                                        name: string;
                                        address: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                        /** Format: date-time */
                                        updatedAt: string;
                                    } | null;
                                    activities: {
                                        /** Format: uuid */
                                        id: string;
                                        dayIndex: number;
                                        name: string;
                                        place: string;
                                        position: number;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    }[];
                                }[];
                                documents: {
                                    passport: {
                                        number: string | null;
                                        expiry: string | null;
                                        hasPhoto: boolean;
                                        photoVersion: string | null;
                                    } | null;
                                    customs: {
                                        code: string;
                                        note: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    } | null;
                                    transports: {
                                        /** Format: uuid */
                                        id: string;
                                        name: string;
                                        reference: string;
                                        /** @enum {string} */
                                        mode: "van" | "flight" | "ferry";
                                        docs: {
                                            /** Format: uuid */
                                            id: string;
                                            label: string;
                                            doc: {
                                                /** Format: uuid */
                                                id: string;
                                                /** @enum {string} */
                                                kind: "pdf" | "image" | "qr";
                                                title: string;
                                                subtitle: string;
                                                code: string;
                                                hasFile: boolean;
                                                originalName: string | null;
                                                mimeType: string | null;
                                                sizeBytes: number | null;
                                                /** Format: date-time */
                                                createdAt: string;
                                            } | null;
                                        }[];
                                    }[];
                                    insurance: {
                                        company: string;
                                        policy: string;
                                        coverage: string;
                                        emergencyPhone: string;
                                        doc: {
                                            /** Format: uuid */
                                            id: string;
                                            /** @enum {string} */
                                            kind: "pdf" | "image" | "qr";
                                            title: string;
                                            subtitle: string;
                                            code: string;
                                            hasFile: boolean;
                                            originalName: string | null;
                                            mimeType: string | null;
                                            sizeBytes: number | null;
                                            /** Format: date-time */
                                            createdAt: string;
                                        } | null;
                                    } | null;
                                };
                                emergencies: {
                                    /** Format: uuid */
                                    id: string;
                                    title: string;
                                    subtitle: string;
                                    actionLabel: string;
                                    phone: string;
                                    whatsapp: boolean;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/trips/{tripId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        invitees: {
                            name: string;
                            /** Format: email */
                            email?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            invitations: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                email: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    invitationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        role: "coordinator" | "traveller";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            member: {
                                /** Format: uuid */
                                userId: string;
                                firstName: string;
                                lastName: string;
                                username: string | null;
                                /** @enum {string} */
                                role: "coordinator" | "traveller";
                                /** Format: date-time */
                                joinedAt: string;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/trips/{tripId}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/invite-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            inviteCode: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            document: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                kind: "pdf" | "image" | "qr";
                                title: string;
                                subtitle: string;
                                code: string;
                                hasFile: boolean;
                                originalName: string | null;
                                mimeType: string | null;
                                sizeBytes: number | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/documents/{documentId}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    documentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                            expiresInSeconds: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    documentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/days/{day}/stay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    day: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        address: string;
                        documentId?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            stay: {
                                name: string;
                                address: string;
                                doc: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    kind: "pdf" | "image" | "qr";
                                    title: string;
                                    subtitle: string;
                                    code: string;
                                    hasFile: boolean;
                                    originalName: string | null;
                                    mimeType: string | null;
                                    sizeBytes: number | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                } | null;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    day: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/days/{day}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    day: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        place: string;
                        documentId?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            activity: {
                                /** Format: uuid */
                                id: string;
                                dayIndex: number;
                                name: string;
                                place: string;
                                position: number;
                                doc: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    kind: "pdf" | "image" | "qr";
                                    title: string;
                                    subtitle: string;
                                    code: string;
                                    hasFile: boolean;
                                    originalName: string | null;
                                    mimeType: string | null;
                                    sizeBytes: number | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                } | null;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    activityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    activityId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        place?: string;
                        dayIndex?: number;
                        documentId?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            activity: {
                                /** Format: uuid */
                                id: string;
                                dayIndex: number;
                                name: string;
                                place: string;
                                position: number;
                                doc: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    kind: "pdf" | "image" | "qr";
                                    title: string;
                                    subtitle: string;
                                    code: string;
                                    hasFile: boolean;
                                    originalName: string | null;
                                    mimeType: string | null;
                                    sizeBytes: number | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                } | null;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/trips/{tripId}/transports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** @default  */
                        reference?: string;
                        /** @enum {string} */
                        mode: "van" | "flight" | "ferry";
                        /** @default [] */
                        docs?: {
                            /** Format: uuid */
                            id?: string;
                            label: string;
                            documentId?: string | null;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            transport: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                reference: string;
                                /** @enum {string} */
                                mode: "van" | "flight" | "ferry";
                                docs: {
                                    /** Format: uuid */
                                    id: string;
                                    label: string;
                                    doc: {
                                        /** Format: uuid */
                                        id: string;
                                        /** @enum {string} */
                                        kind: "pdf" | "image" | "qr";
                                        title: string;
                                        subtitle: string;
                                        code: string;
                                        hasFile: boolean;
                                        originalName: string | null;
                                        mimeType: string | null;
                                        sizeBytes: number | null;
                                        /** Format: date-time */
                                        createdAt: string;
                                    } | null;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/transports/{transportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    transportId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** @default  */
                        reference?: string;
                        /** @enum {string} */
                        mode: "van" | "flight" | "ferry";
                        /** @default [] */
                        docs?: {
                            /** Format: uuid */
                            id?: string;
                            label: string;
                            documentId?: string | null;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            transport: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                reference: string;
                                /** @enum {string} */
                                mode: "van" | "flight" | "ferry";
                                docs: {
                                    /** Format: uuid */
                                    id: string;
                                    label: string;
                                    doc: {
                                        /** Format: uuid */
                                        id: string;
                                        /** @enum {string} */
                                        kind: "pdf" | "image" | "qr";
                                        title: string;
                                        subtitle: string;
                                        code: string;
                                        hasFile: boolean;
                                        originalName: string | null;
                                        mimeType: string | null;
                                        sizeBytes: number | null;
                                        /** Format: date-time */
                                        createdAt: string;
                                    } | null;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    transportId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/insurance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        company: string;
                        policy: string;
                        /** @default  */
                        coverage?: string;
                        emergencyPhone?: "" | string;
                        documentId?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            insurance: {
                                company: string;
                                policy: string;
                                coverage: string;
                                emergencyPhone: string;
                                doc: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    kind: "pdf" | "image" | "qr";
                                    title: string;
                                    subtitle: string;
                                    code: string;
                                    hasFile: boolean;
                                    originalName: string | null;
                                    mimeType: string | null;
                                    sizeBytes: number | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                } | null;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/customs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        /** @default  */
                        note?: string;
                        documentId?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            customs: {
                                code: string;
                                note: string;
                                doc: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    kind: "pdf" | "image" | "qr";
                                    title: string;
                                    subtitle: string;
                                    code: string;
                                    hasFile: boolean;
                                    originalName: string | null;
                                    mimeType: string | null;
                                    sizeBytes: number | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                } | null;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/emergencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        contacts: {
                            title: string;
                            /** @default  */
                            subtitle?: string;
                            actionLabel: string;
                            phone: string;
                            /** @default false */
                            whatsapp?: boolean;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            emergencies: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                subtitle: string;
                                actionLabel: string;
                                phone: string;
                                whatsapp: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    day?: number;
                    author?: "me" | string;
                    kind?: "media" | "note";
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            memories: ({
                                /** Format: uuid */
                                id: string;
                                dayIndex: number;
                                /** Format: uuid */
                                authorId: string;
                                /** @enum {string} */
                                visibility: "crew" | "private";
                                /** Format: date-time */
                                createdAt: string;
                                /** @enum {string} */
                                kind: "photo" | "video";
                                caption: string | null;
                                aspectRatio: number;
                                blurhash: string | null;
                                durationSeconds: number | null;
                                mimeType: string;
                                mediaUrl: string | null;
                                reactions: {
                                    fire?: number;
                                    laugh?: number;
                                    love?: number;
                                    mindblown?: number;
                                };
                                myReaction: ("fire" | "laugh" | "love" | "mindblown") | null;
                            } | {
                                /** Format: uuid */
                                id: string;
                                dayIndex: number;
                                /** Format: uuid */
                                authorId: string;
                                /** @enum {string} */
                                visibility: "crew" | "private";
                                /** Format: date-time */
                                createdAt: string;
                                /** @enum {string} */
                                kind: "note";
                                text: string;
                                /** @enum {string} */
                                mood: "anecdote" | "place" | "thought" | "personal";
                            })[];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            memory: {
                                /** Format: uuid */
                                id: string;
                                dayIndex: number;
                                /** Format: uuid */
                                authorId: string;
                                /** @enum {string} */
                                visibility: "crew" | "private";
                                /** Format: date-time */
                                createdAt: string;
                                /** @enum {string} */
                                kind: "photo" | "video";
                                caption: string | null;
                                aspectRatio: number;
                                blurhash: string | null;
                                durationSeconds: number | null;
                                mimeType: string;
                                mediaUrl: string | null;
                                reactions: {
                                    fire?: number;
                                    laugh?: number;
                                    love?: number;
                                    mindblown?: number;
                                };
                                myReaction: ("fire" | "laugh" | "love" | "mindblown") | null;
                            } | {
                                /** Format: uuid */
                                id: string;
                                dayIndex: number;
                                /** Format: uuid */
                                authorId: string;
                                /** @enum {string} */
                                visibility: "crew" | "private";
                                /** Format: date-time */
                                createdAt: string;
                                /** @enum {string} */
                                kind: "note";
                                text: string;
                                /** @enum {string} */
                                mood: "anecdote" | "place" | "thought" | "personal";
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/memories/{memoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    memoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    memoryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text?: string;
                        caption?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            memory: {
                                /** Format: uuid */
                                id: string;
                                dayIndex: number;
                                /** Format: uuid */
                                authorId: string;
                                /** @enum {string} */
                                visibility: "crew" | "private";
                                /** Format: date-time */
                                createdAt: string;
                                /** @enum {string} */
                                kind: "photo" | "video";
                                caption: string | null;
                                aspectRatio: number;
                                blurhash: string | null;
                                durationSeconds: number | null;
                                mimeType: string;
                                mediaUrl: string | null;
                                reactions: {
                                    fire?: number;
                                    laugh?: number;
                                    love?: number;
                                    mindblown?: number;
                                };
                                myReaction: ("fire" | "laugh" | "love" | "mindblown") | null;
                            } | {
                                /** Format: uuid */
                                id: string;
                                dayIndex: number;
                                /** Format: uuid */
                                authorId: string;
                                /** @enum {string} */
                                visibility: "crew" | "private";
                                /** Format: date-time */
                                createdAt: string;
                                /** @enum {string} */
                                kind: "note";
                                text: string;
                                /** @enum {string} */
                                mood: "anecdote" | "place" | "thought" | "personal";
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/trips/{tripId}/memories/{memoryId}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    memoryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        reaction: "fire" | "laugh" | "love" | "mindblown";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reactions: {
                                fire?: number;
                                laugh?: number;
                                love?: number;
                                mindblown?: number;
                            };
                            myReaction: ("fire" | "laugh" | "love" | "mindblown") | null;
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    memoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reactions: {
                                fire?: number;
                                laugh?: number;
                                love?: number;
                                mindblown?: number;
                            };
                            myReaction: ("fire" | "laugh" | "love" | "mindblown") | null;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/memories/{memoryId}/media-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: string;
                    memoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                            expiresInSeconds: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            trip: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                /** Format: date */
                                startDate: string;
                                /** Format: date */
                                endDate: string;
                                totalDays: number;
                                crewCount: number;
                                crewCapacity: number | null;
                                coordinators: {
                                    firstName: string;
                                    lastName: string;
                                }[];
                            };
                            alreadyMember: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{code}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            tripId: string;
                            joined: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
